spring:
  application:
    name: BlogApplication
  datasource:
    url: jdbc:mysql://192.168.106.128:3306/blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    port: 6379
    host: 192.168.106.128
    password: 123456
    database: 1
  data:
    solr:
      host: http://192.168.106.128:8983/solr/blog_core
server:
  port: 8082

# docker部署
# 应该是docker内部的路径 映射 /home/spike/docker/Blog/upload
# blog.image.save-path: /usr/app/upload
blog.image.save-path: D:\Codes\BlogSystem\logs\images
# 2MB
blog.image.max-size: 2097152
# swagger
blog.swagger.enable: true


