spring:
  application:
    name: BlogApplication
  datasource:
    url: jdbc:mysql://172.24.212.100:3306/blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: false
  redis:
    port: 6379
    host: 172.24.212.100
    password: 123456
    database: 1
  data:
    solr:
      host: http://172.24.212.100:8983/solr/sob_blog_core
server:
  port: 8080
# docker部署
# 应该是docker内部的路径 映射 /home/spike/docker/Blog/upload
# blog.image.save-path: /usr/app/upload
blog.image.save-path: /root/docker/imageUpload
# 2MB
blog.image.max-size: 2097152
# swagger
blog.swagger.enable: false


