spring:
  application:
    name: BlogApplication
  datasource:
    url: jdbc:mysql://192.168.106.128:3306/blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    port: 6379
    host: 192.168.106.128
    password: 123456
  data:
    solr:
      host: http://192.168.106.128:8983/solr/blog_core
server:
  port: 8082

blog.image.save-path: \user\spike\Blog\images
# 5MB
blog.image.max-size: 2097152


