spring:
  application:
    name: BlogApplication
  datasource:
    url: jdbc:mysql://172.24.212.100:3306/blog?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
server:
  port: 8080



